# Generated by Django 4.1.7 on 2023-03-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('region', models.CharField(choices=[('NA', 'North America')], max_length=2)),
                ('moderator', models.BooleanField()),
            ],
        ),
    ]
